// Code generated by mockery v2.22.1. DO NOT EDIT.

package mocks

import (
	board "to-do-api/pg/domain/board"

	mock "github.com/stretchr/testify/mock"
)

// BoardRepository is an autogenerated mock type for the BoardRepository type
type BoardRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: _a0
func (_m *BoardRepository) Create(_a0 board.Board) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(board.Board) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: _a0
func (_m *BoardRepository) Delete(_a0 uint) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(uint) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindAll provides a mock function with given fields:
func (_m *BoardRepository) FindAll() (*board.DTO, error) {
	ret := _m.Called()

	var r0 *board.DTO
	var r1 error
	if rf, ok := ret.Get(0).(func() (*board.DTO, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *board.DTO); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*board.DTO)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: _a0
func (_m *BoardRepository) GetByID(_a0 uint) (*board.Board, error) {
	ret := _m.Called(_a0)

	var r0 *board.Board
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (*board.Board, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(uint) *board.Board); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*board.Board)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: _a0
func (_m *BoardRepository) Update(_a0 board.Board) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(board.Board) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewBoardRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewBoardRepository creates a new instance of BoardRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewBoardRepository(t mockConstructorTestingTNewBoardRepository) *BoardRepository {
	mock := &BoardRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
